[package]
name = "distpow"
version = "0.1.0"
authors = ["Scott <dscottwiggins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2.0"

[lib]
crate-type = ["cdylib"]
